### ISSUE TITLE
[Linux] linking error undefined reference to `main'

### ISSUE THREAD

**Issue by KottV** [christofmuc/BCR2000_Master#1]
Hi,

I'm trying to build under Linux. I've got through some missed -l -f flags, but last error is unclear:

> 
> [ 69%] Linking CXX executable BCRMaster
> /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/9/../../../../lib64/crt1.o: in function `_start':
> /home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
> collect2: error: ld returned 1 exit status
> make[2]: *** [BCRMaster/CMakeFiles/BCRMaster.dir/build.make:302: BCRMaster/BCRMaster] Error 1
> make[1]: *** [CMakeFiles/Makefile2:307: BCRMaster/CMakeFiles/BCRMaster.dir/all] Error 2
> make: *** [Makefile:101: all] Error 2

I think something wrong with juce's cmake. It doesn't  find main() in there.

**Comment by christofmuc** [comment]
Thank you! Linux never was done, can you try again with a new master? I merged PR #2

**Comment by KottV** [comment]
Great, it compiles now!
I had to to restore PkgConfig::WEBKIT because it was missed in final linkage.

**Comment by christofmuc** [comment]
Thank you, I added that as well, so it should build out of the box! Will try to add a README, just realized it still is missing.

**Comment by KottV** [comment]
Thank You!
